[workspace]
members = [
    "redeem-classifiers",
    "redeem-cli",
    "redeem-properties",
    "redeem-properties-py",
]

resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = true
